<?php
if (function_exists('acf_add_local_field_group')) :

	acf_add_local_field_group(array(
		'key' => 'group_62d99e16ec710',
		'title' => 'Options',
		'fields' => array(
			array(
				'key' => 'field_62d9b2823de3e',
				'label' => 'General theme settings',
				'name' => '',
				'type' => 'tab',
				'instructions' => '',
				'required' => 0,
				'conditional_logic' => 0,
				'wrapper' => array(
					'width' => '',
					'class' => '',
					'id' => '',
				),
				'placement' => 'top',
				'endpoint' => 0,
			),
			array(
				'key' => 'field_62d99e3b4c9ad',
				'label' => 'Predefined colors',
				'name' => 'predefined_colors',
				'type' => 'repeater',
				'instructions' => '',
				'required' => 0,
				'conditional_logic' => 0,
				'wrapper' => array(
					'width' => '',
					'class' => '',
					'id' => '',
				),
				'collapsed' => '',
				'min' => 0,
				'max' => 0,
				'layout' => 'table',
				'button_label' => 'Add color',
				'library_type' => 0,
				'sub_fields' => array(
					array(
						'key' => 'field_62d99e6a4c9ae',
						'label' => 'Label',
						'name' => 'label',
						'type' => 'text',
						'instructions' => '',
						'required' => 0,
						'conditional_logic' => 0,
						'wrapper' => array(
							'width' => '',
							'class' => '',
							'id' => '',
						),
						'default_value' => '',
						'placeholder' => '',
						'prepend' => '',
						'append' => '',
						'maxlength' => '',
					),
					array(
						'key' => 'field_62d99e6f4c9af',
						'label' => 'Color',
						'name' => 'color',
						'type' => 'color_picker',
						'instructions' => '',
						'required' => 0,
						'conditional_logic' => 0,
						'wrapper' => array(
							'width' => '',
							'class' => '',
							'id' => '',
						),
						'default_value' => '',
						'enable_opacity' => 0,
						'return_format' => 'string',
					),
				),
			),
		),
		'location' => array(
			array(
				array(
					'param' => 'options_page',
					'operator' => '==',
					'value' => 'acf-options-theme-settings',
				),
			),
		),
		'menu_order' => 0,
		'position' => 'normal',
		'style' => 'default',
		'label_placement' => 'top',
		'instruction_placement' => 'label',
		'hide_on_screen' => '',
		'active' => true,
		'description' => '',
		'show_in_rest' => 0,
	));

	acf_add_local_field_group(array(
		'key' => 'group_618fa3e1aae4b',
		'title' => 'Ustawienia bloku',
		'fields' => array(
			array(
				'key' => 'field_618fa9429fbf7',
				'label' => 'Ustawienia dodatkowe',
				'name' => '',
				'type' => 'accordion',
				'instructions' => '',
				'required' => 0,
				'conditional_logic' => 0,
				'wrapper' => array(
					'width' => '',
					'class' => '',
					'id' => '',
				),
				'open' => 0,
				'multi_expand' => 0,
				'endpoint' => 0,
			),
			array(
				'key' => 'field_618fa4032fe0d',
				'label' => 'Ustawienia ułożenia',
				'name' => 'ustawienia_ulozenia',
				'type' => 'group',
				'instructions' => '',
				'required' => 0,
				'conditional_logic' => 0,
				'wrapper' => array(
					'width' => '',
					'class' => '',
					'id' => '',
				),
				'layout' => 'block',
				'sub_fields' => array(
					array(
						'key' => 'field_65981e1fae3cf',
						'label' => 'Kotwica',
						'name' => 'kotwica',
						'aria-label' => '',
						'type' => 'text',
						'instructions' => '',
						'required' => 0,
						'conditional_logic' => 0,
						'wrapper' => array(
							'width' => '',
							'class' => '',
							'id' => '',
						),
						'default_value' => '',
						'maxlength' => '',
						'placeholder' => '',
						'prepend' => '',
						'append' => '',
					),
					array(
						'key' => 'field_65981dffae3ce',
						'label' => 'Typ tła',
						'name' => 'typ_tla',
						'aria-label' => '',
						'type' => 'button_group',
						'instructions' => '',
						'required' => 0,
						'conditional_logic' => 0,
						'wrapper' => array(
							'width' => '',
							'class' => '',
							'id' => '',
						),
						'choices' => array(
							1 => 'grafika',
							2 => 'video',
						),
						'default_value' => 1,
						'return_format' => 'value',
						'allow_null' => 0,
						'layout' => 'horizontal',
					),
					array(
						'key' => 'field_65981e3dae3d0',
						'label' => 'Tło graficzne',
						'name' => 'tlo_graficzne',
						'aria-label' => '',
						'type' => 'image',
						'instructions' => '',
						'required' => 0,
						'conditional_logic' => array(
							array(
								array(
									'field' => 'field_65981dffae3ce',
									'operator' => '==',
									'value' => '1',
								),
							),
						),
						'wrapper' => array(
							'width' => '',
							'class' => '',
							'id' => '',
						),
						'return_format' => 'url',
						'library' => 'all',
						'min_width' => '',
						'min_height' => '',
						'min_size' => '',
						'max_width' => '',
						'max_height' => '',
						'max_size' => '',
						'mime_types' => '',
						'preview_size' => 'medium',
					),
					array(
						'key' => 'field_65981f67a31be',
						'label' => 'Poster',
						'name' => 'poster',
						'aria-label' => '',
						'type' => 'image',
						'instructions' => '',
						'required' => 0,
						'conditional_logic' => array(
							array(
								array(
									'field' => 'field_65981dffae3ce',
									'operator' => '==',
									'value' => '2',
								),
							),
						),
						'wrapper' => array(
							'width' => '',
							'class' => '',
							'id' => '',
						),
						'return_format' => 'url',
						'library' => 'all',
						'min_width' => '',
						'min_height' => '',
						'min_size' => '',
						'max_width' => '',
						'max_height' => '',
						'max_size' => '',
						'mime_types' => '',
						'preview_size' => 'medium',
					),
					array(
						'key' => 'field_65981f4ba31bd',
						'label' => 'Video',
						'name' => 'video',
						'aria-label' => '',
						'type' => 'file',
						'instructions' => '',
						'required' => 0,
						'conditional_logic' => array(
							array(
								array(
									'field' => 'field_65981dffae3ce',
									'operator' => '==',
									'value' => '2',
								),
							),
						),
						'wrapper' => array(
							'width' => '',
							'class' => '',
							'id' => '',
						),
						'return_format' => 'url',
						'library' => 'all',
						'min_size' => '',
						'max_size' => '',
						'mime_types' => '',
					),
					array(
						'key' => 'field_65981e4fae3d1',
						'label' => 'Overlay',
						'name' => 'overlay',
						'aria-label' => '',
						'type' => 'color_picker',
						'instructions' => '',
						'required' => 0,
						'conditional_logic' => 0,
						'wrapper' => array(
							'width' => '',
							'class' => '',
							'id' => '',
						),
						'default_value' => '',
						'enable_opacity' => 1,
						'return_format' => 'string',
					),
					array(
						'key' => 'field_65981dffsae3ce',
						'label' => 'Warstwa mieszania',
						'name' => 'type_mix_blend',
						'aria-label' => '',
						'type' => 'button_group',
						'instructions' => '',
						'required' => 0,
						'conditional_logic' => array(
							array(
								array(
									'field' => 'field_65981e4fae3d1',
									'operator' => '!=empty',
								),
							),
						),
						'choices' => array(
							'video_image' => 'Video/grafika',
							'overlay' => 'overlay',
						),
						'default_value' => 1,
						'return_format' => 'value',
						'allow_null' => 0,
						'layout' => 'horizontal',
					),
					array(
						'key' => 'field_65981eb1ae3d2',
						'label' => 'Typ mieszania',
						'name' => 'typ_mieszania',
						'aria-label' => '',
						'type' => 'select',
						'instructions' => '',
						'required' => 0,
						'conditional_logic' => array(
							array(
								array(
									'field' => 'field_65981e4fae3d1',
									'operator' => '!=empty',
								),
							),
						),
						'wrapper' => array(
							'width' => '',
							'class' => '',
							'id' => '',
						),
						'choices' => array(
							'normal' => 'Oryginalne kolory.',
							'multiply' => 'Ciemniejsze mieszanie.',
							'screen' => 'Jasniejsze mieszanie.',
							'overlay' => 'Mieszanie nakładające.',
							'darken' => 'Ciemniejszy kolor dominuje.',
							'lighten' => 'Jasniejszy kolor dominuje.',
							'color-dodge' => 'Rozjaśnianie dolnego koloru.',
							'color-burn' => 'Przyciemnianie dolnego koloru.',
							'hard-light' => 'Mocne światło.',
							'soft-light' => 'Miękkie światło.',
							'difference' => 'Różnica kolorów.',
							'exclusion' => 'Wykluczenie kolorów.',
							'hue' => 'Mieszanie barw.',
							'saturation' => 'Mieszanie nasycenia.',
							'color' => 'Mieszanie kolorów.',
							'luminosity' => 'Mieszanie jasności.',
						),
						'default_value' => 'normal',
						'return_format' => 'value',
						'multiple' => 0,
						'allow_null' => 0,
						'ui' => 0,
						'ajax' => 0,
						'placeholder' => '',
					),
				),
array(
	'key' => 'field_65981e4fae3d1',
	'label' => 'Overlay',
	'name' => 'overlay',
	'aria-label' => '',
	'type' => 'color_picker',
	'instructions' => '',
	'required' => 0,
	'conditional_logic' => 0,
	'wrapper' => array(
		'width' => '',
		'class' => '',
		'id' => '',
	),
	'default_value' => '',
	'enable_opacity' => 1,
	'return_format' => 'string',
),
),
),
'location' => array(
	array(
		array(
			'param' => 'block',
			'operator' => '==',
			'value' => 'all',
		),
	),
),
'menu_order' => 99,
'position' => 'normal',
'style' => 'default',
'label_placement' => 'top',
'instruction_placement' => 'label',
'hide_on_screen' => '',
'active' => true,
'description' => '',
'show_in_rest' => 0,
));

endif;





